"""
從 taptaploot_clicker.py 的 __version__ 生成 PyInstaller 用的 version_info.txt。
build.bat 會在打包前自動呼叫此腳本。
"""
from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).parent
SRC = ROOT / "taptaploot_clicker.py"
OUT = ROOT / "version_info.txt"
VERSION_FILE = ROOT / "VERSION"


def parse_version() -> tuple[str, tuple[int, int, int, int]]:
    text = SRC.read_text(encoding="utf-8")
    m = re.search(r'__version__\s*=\s*"([^"]+)"', text)
    if not m:
        sys.exit("無法在 taptaploot_clicker.py 找到 __version__")
    version_str = m.group(1)

    # Convert "1.2.3" -> (1, 2, 3, 0)
    parts = re.split(r"[.\-+]", version_str)
    nums: list[int] = []
    for p in parts:
        try:
            nums.append(int(re.match(r"\d+", p).group()))
        except (AttributeError, ValueError):
            break
    while len(nums) < 4:
        nums.append(0)
    return version_str, tuple(nums[:4])


TEMPLATE = """\
# UTF-8
# Auto-generated by _make_version_info.py — do NOT edit manually.
VSVersionInfo(
  ffi=FixedFileInfo(
    filevers={tup},
    prodvers={tup},
    mask=0x3f,
    flags=0x0,
    OS=0x40004,
    fileType=0x1,
    subtype=0x0,
    date=(0, 0)
  ),
  kids=[
    StringFileInfo([
      StringTable(
        u'040904B0',
        [
          StringStruct(u'CompanyName', u'TapTapLoot Auto Clicker'),
          StringStruct(u'FileDescription', u'TapTapLoot Auto Clicker'),
          StringStruct(u'FileVersion', u'{ver}'),
          StringStruct(u'InternalName', u'TapTapLootClicker'),
          StringStruct(u'LegalCopyright', u'MIT License'),
          StringStruct(u'OriginalFilename', u'TapTapLootClicker.exe'),
          StringStruct(u'ProductName', u'TapTapLoot Auto Clicker'),
          StringStruct(u'ProductVersion', u'{ver}')
        ])
    ]),
    VarFileInfo([VarStruct(u'Translation', [1033, 1200])])
  ]
)
"""


def main() -> None:
    ver_str, ver_tuple = parse_version()
    OUT.write_text(TEMPLATE.format(tup=ver_tuple, ver=ver_str), encoding="utf-8")
    # 同步寫一個純文字 VERSION 檔給 build.bat 讀（避免 for /f + python 單行的跨層 escape 問題）
    VERSION_FILE.write_text(ver_str, encoding="ascii")
    print(f"已生成 {OUT.name} 與 {VERSION_FILE.name}: v{ver_str} {ver_tuple}")


if __name__ == "__main__":
    main()
